#!/bin/bash

for node in cdc0004 cdc0005 cdc0006 cdc0007 cdc0008 cdc0009 cdc0010 cdc0011
do
  knife role run_list clear ${node}_lab_fewt_com
  knife role run_list add ${node}_lab_fewt_com "recipe[rancher::rancher_server]"
  ssh -ttq ${node}.lab.fewt.com sudo chef-client
done
