#!/bin/bash

###
### Extend lv_var, grab the JumpCloud CA certificate, and provision the Rancher server.
###

###
### Rancher 1.0
###

#ssh -ttq cdc0004.lab.fewt.com <<EOF
#  WD=`pwd`
#  sudo lvextend -rL +10G /dev/sysvg/lv_var
#  echo -n | openssl s_client -connect ldap.jumpcloud.com:636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ${WD}/ca.crt
#  sudo docker run -d --restart=unless-stopped -p 8080:8080 -v ${WD}/cert.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server
#EOF

###
### Rancher 2.0
###

ssh -ttq cdc0004.lab.fewt.com <<EOF
  WD=`pwd`
  sudo lvextend -rL +10G /dev/sysvg/lv_var
  sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
EOF
