#!/bin/bash

if [ ! $1 ]
then
  echo -n "Enter the Rancher URL from the Add Host screen: "
  read RANCHER_URL
else
  RANCHER_URL=$1
fi

for node in $(seq -f %04g 4 1 11)
do
  ssh -ttq cdc${node}.lab.fewt.com sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 "${RANCHER_URL}"
done
