#!/bin/bash

###
### Extend lv_var, grab the JumpCloud CA certificate, and provision the Rancher server.
###

ssh -ttq cdc0004.lab.fewt.com <<EOF
  WD=`pwd`
  sudo lvextend -rL +10G /dev/sysvg/lv_var
  echo -n | openssl s_client -connect ldap.jumpcloud.com:636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ${WD}/ca.crt
  sudo docker run -d --restart=unless-stopped -p 8080:8080 -v ${WD}/cert.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server
EOF
