#!/bin/bash

if [ ! $1 ]
then
  echo -n "Enter the Rancher Token: "
  read RANCHER_TOKEN
else
  RANCHER_TOKEN=$1
fi

if [ ! $2 ]
then
  echo -n "Enter the CA Checksum: "
  read RANCHER_CA
else
  RANCHER_CA=$2
fi

for node in $(seq -f %04g 5 1 8)
do
  ssh -ttq cdc${node}.lab.fewt.com <<EOF
    sudo lvextend -rL +10G /dev/sysvg/lv_var
    sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.0.8 --server https://cdc0004.lab.fewt.com --token "${RANCHER_TOKEN}" --ca-checksum "${RANCHER_CA}" --worker
    exit
EOF
done

