#!/bin/bash

###
### Experimenting with hostname randomization.
###

for node in $(seq -f %04g 1 1 11)
do
  ssh -ttq cdc${node}.lab.fewt.com "sudo cat /sys/class/dmi/id/product_serial /sys/class/dmi/id/product_uuid | sha1sum | awk '{print substr (\$1, 0, 15)}'"
done
