name 'rancher'
maintainer 'Andrew Wyatt'
maintainer_email 'andrew@fuduntu.org'
license 'Apache-2.0'
description 'Deploys Rancher to the environment'
long_description 'Deploys Rancher to the environment'
version '0.0.1'
chef_version '>= 12.14' if respond_to?(:chef_version)
depends 'lab_management'
supports 'redhat'
source_url 'https://github.com/andrewwyatt/tilde-slash-lab'
issues_url 'https://github.com/andrewwyatt/tilde-slash-lab/issues'
